// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajgyrhddxljfauwneput.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqZ3lyaGRkeGxqZmF1d25lcHV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MTcyOTMsImV4cCI6MjA3MjM5MzI5M30.tniaCIQSSwKwNcJWt4yRsGunNeQk_g6ex02WRi3qOQ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});